language: python
python:
  - 2.7

services:
  - docker

hosts:
  - feed.bencane.com
  - bencane.com

install:
  - docker build -t blog .
  - docker run -d -p 127.0.0.1:80:80 --name blog blog

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser
  - pip install coverage
  - pip install coveralls


script:
  - docker ps | grep -q blog
