author: madflojo
date: 2016-11-15 11:15:00-07:00
pubdate: Tue, 15 Oct 2016 11:15:00 -07:00
popularity: False
title: Performance Tuning HAProxy
description: Let's explore some performance-tuning concepts and walk through some tuning options for HAProxy, installing and configuring HAProxy as a load balancer.
post_id: 138
categories:
  - performance tuning
tags:
  - haproxy
  - load balancing
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/performance-tuning-haproxy/
read_time: 11
published: True
