author: madflojo
date: 2016-04-27 11:15:00-07:00
pubdate: Wed, 27 Apr 2016 11:15:00 -07:00
popularity: False
title: Getting started with Kubernetes
description: Let's learn about Kubernetes by deploying a simple web application across a multinode Kubernetes cluster.
post_id: 130
categories:
  - containers
tags:
  - docker
  - kubernetes
  - vagrant
  - web application
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/getting-started-with-kubernetes/
read_time: 10
published: True
