author: madflojo
date: 2016-10-06 11:15:00-07:00
pubdate: Thurs, 06 Oct 2016 11:15:00 -07:00
popularity: False
title: Pregenerating Static Web Pages for Better Performance
description: Let's increase our web application's performance by pregenerating the results of our "dynamic" pages and saving those results into a file cache.
post_id: 137
categories:
  - performance tuning
tags:
  - nginx
  - static pages
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/pregenerating-static-web-pages-for-better-performance/
read_time: 10
published: True
