author: madflojo
date: 2016-05-31 11:15:00-07:00
pubdate: Tues, 31 May 2016 11:15:00 -07:00
popularity: False
title: Ensuring Containers Are Always Running with Docker's Restart Policy
description: In today's article we will discuss how to use Docker&#039;s restart policy to automatically restart containers and avoid those late-night notifications.
post_id: 132
categories:
  - containers
tags:
  - docker
  - automated restart
  - on call
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/ensuring-containers-are-always-running-with-dockers-restart-policy/
read_time: 9
published: True
