author: madflojo
date: 2017-05-18 11:15:00-07:00
pubdate: Thur, 18 May 2017 11:15:00 -07:00
popularity: False
title: Leveraging the dockerignore File to Create Smaller Images
description: There are several techniques for keeping images small. In today's article, we will explore an often-ignored technique, using the dockerignore file.
post_id: 144
categories:
  - containers
tags:
  - docker
  - .dockerignore
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/leveraging-the-dockerignore-file-to-create-smaller-images/
read_time: 7
published: True
