author: madflojo
date: 2017-07-24 11:15:00-07:00
pubdate: Thurs, 24 Jul 2017 11:15:00 -07:00
popularity: False
title: Eliminate the Database for Higher Availability
description: Read about a design strategy unique to platforms that require both high scalability and high availability. A design strategy that involves reducing and removing the need for databases.
post_id: 147
categories:
  - architecture
tags:
  - systems architecture
file: False
external: True
publisher: AmericanExpress.io
remote_url: http://americanexpress.io/eliminate-the-database-for-higher-availability/
read_time: 12
published: True
