author: madflojo
date: 2017-12-18 11:15:00-07:00
pubdate: Mon, 14 Dec 2017 11:15:00 -07:00
popularity: False
title: Using the Add-Host Flag for DNS Mapping within Docker Containers
description: Let's explore a single Docker run command option, specifically, the add-host flag, which allows us to change DNS within a container.
post_id: 151
categories:
  - containers
tags:
  - docker
  - docker dns
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/using-the-add-host-flag-for-dns-mapping-within-docker-containers/
read_time: 6
published: True
