author: madflojo
date: 2017-08-22 11:15:00-07:00
pubdate: Tue, 22 Aug 2017 11:15:00 -07:00
popularity: False
title: The Basics of the Docker Run Command
description: Get back to the basics and explore a few simple docker run examples. Here, we demonstrate various ways to start a container instance.
post_id: 148
categories:
  - containers
tags:
  - docker
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/the-basics-of-the-docker-run-command/
read_time: 6
published: True
