author: madflojo
date: 2018-01-30 11:15:00-07:00
pubdate: Tue, 30 Jan 2018 11:15:00 -07:00
popularity: True
title: Easy Container Cleanup in Cron + Docker Environments
description: Let's explore two flags that make it easier to run Dockerized Cron jobs, as well as how we would traditionally create and clean up a Docker container.
post_id: 152
categories:
  - containers
tags:
  - docker
  - cron
file: False
external: True
publisher: Codeship
remote_url: https://blog.codeship.com/easy-container-cleanup-in-cron-docker-environments/
read_time: 6
published: True
