baseURL: 'https://bencane.com/'
title: Benjamin Cane
paginate: 5
theme: hugo-PaperMod
enableRobotsTXT: true
googleAnalytics: UA-3378969-11

params:
  description: 'Distributed Systems and Software Engineer'
  author: Benjamin Cane
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  profileMode:
    enabled: false
    imageUrl: 'img/bcane-train.jpg'
    imageTitle: Benjamin Cane
    buttons:
      - name: Archives
        url: post

  homeInfoParams:
    Title: "Hi \U0001F44B"
    Content: "My name is Benjamin Cane, and you've landed on my engineering blog. I have a background in distributed systems operations, architecture, and development. You will find articles about all sorts of topics like Docker, Linux, Go, Python, and lots more. I hope you enjoy the blog."

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/madflojo'
    - name: medium
      url: 'https://medium.com/@madflojo'
    - name: linkedin
      url: 'https://www.linkedin.com/in/bencane/'
    - name: github
      url: 'https://github.com/madflojo'

menu:
  main:
    - name: Archives
      url: /post/
      weight: 5
    - name: Talks
      url: /talks/
      weight: 6
    - name: Books
      url: /books/
      weight: 7
    - name: Buy Me A Coffee
      url: https://www.buymeacoffee.com/madflojo
      weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

